# Generated by Django 5.0.3 on 2024-03-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='dummy@eureos.de', max_length=255)),
                ('problemtype', models.CharField(default='KeinProblemGewählt', max_length=400)),
                ('problemdescription', models.CharField(default='Keine Beschreibung gegeben.', max_length=20000)),
            ],
        ),
    ]
