# Generated by Django 4.2.11 on 2024-03-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tix', '0003_ticket_created_on_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='added_by',
            field=models.CharField(default='Max Mustermann', max_length=200),
        ),
    ]
