# Generated by Django 4.2.11 on 2024-03-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tix', '0005_ticket_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='Max Mustermann', max_length=255),
        ),
    ]
